[build]
builder = "dockerfile"

[deploy]
restartPolicyType   = "on_failure"
restartPolicyMaxRetries = 3

[variables]
SECRET_KEY_BASE     = "${{ secret(64) }}"
ENCRYPTION_KEY      = "${{ secret(32) }}"
HYDRA_SECRETS_SYSTEM = "${{ secret(32) }}"
RAILS_ENV           = "production"
RAILS_LOG_LEVEL      = "info"
